### ISSUE TITLE
Did Everything correct, still getting this error.

### ISSUE THREAD

**Issue by shreyasbhardwaj** [peppelongo96/UnicalDown#2]
Video URLs: [
  'https://web.microsoftstream.com/video/473620f6-f915-493d-a9fd-f37f3a0e87cd'
]
Username: fiscalcode
Output Directory: videos

Reusing password saved in system's keychain!

Launching headless Chromium to perform the OpenID Connect dance...
...Navigating to Microsoft Stream login page...
...Logging in...
(node:603) UnhandledPromiseRejectionWarning: TimeoutError: waiting for target failed: timeout 100000ms exceeded
    at Object.waitWithTimeout (/Users/macbookair/Downloads/UnicalDown/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:156:26)
    at Browser.waitForTarget (/Users/macbookair/Downloads/UnicalDown/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:269:45)
    at downloadVideo (/Users/macbookair/Downloads/UnicalDown/unicaldown.js:158:17)
(node:603) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:603) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by peppelongo96** [comment]
Hi man, 

you are using the sample command line in Readme file. This certainly never will work.
First, for the correct usage of UnicalDown, please be sure that you are an Unical user. At this time, substitute `fiscalcode` argument with your italian fiscal code (or something similar which Unical assigned to you, if you are an international student). Now all will go well.
Also, you can change the default output directory using `-o` option, as you always can see in [default usage](https://github.com/peppelongo96/UnicalDown#default-usage) section.
